import "./globals.css";
import Navbar from "@/components/navbar/MainNavBar";
import ConnectSection from "@/components/footer/ConnectSection";
import Footer from "@/components/footer/Footer";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body      >
        <Navbar/>
        {children}
        <ConnectSection />
        <Footer />
      </body>
    </html>
  );
}
